const CATEGORIES = Object.freeze({
  RESOURCES: 'resources',
  FACILITIES: 'facilities',
  MOON: 'moon',
});

/**
 * Every building of the game, keyed by the id used by this library.
 *
 * Ids 1 to 5 are historical and kept for backward compatibility; every other
 * entry uses the id OGame itself uses. `ogameId` always holds the official id,
 * so it is the field to rely on when talking to the game.
 *
 * - `names` holds the localised labels.
 * - `factor` is the per-level cost multiplier: cost(level) = base * factor ** (level - 1).
 * - `base` holds the level 1 values, with every energy and deuterium flow named
 *   after what it actually is:
 *   - `metal` / `crystal` / `deuterium` — the resources paid to build it,
 *   - `energyCost` — the energy paid to build it (Terraformer and Space Dock only),
 *   - `energyConsumption` — the energy it consumes once built (mines),
 *   - `deuteriumConsumption` — the deuterium it burns once built (Fusion Reactor),
 *   - `production` — what it produces, resources or energy.
 */
const BUILDINGS = Object.freeze({
  1: {
    ogameId: 1,
    names: { en: 'Metal Mine', fr: 'Mine de métal' },
    category: CATEGORIES.RESOURCES,
    factor: 1.5,
    base: {
      metal: 60,
      crystal: 15,
      deuterium: 0,
      energyCost: 0,
      energyConsumption: 10,
      deuteriumConsumption: 0,
      production: 30,
    },
  },
  2: {
    ogameId: 2,
    names: { en: 'Crystal Mine', fr: 'Mine de cristal' },
    category: CATEGORIES.RESOURCES,
    factor: 1.6,
    base: {
      metal: 48,
      crystal: 24,
      deuterium: 0,
      energyCost: 0,
      energyConsumption: 10,
      deuteriumConsumption: 0,
      production: 20,
    },
  },
  3: {
    ogameId: 3,
    names: { en: 'Deuterium Synthesizer', fr: 'Synthétiseur de deutérium' },
    category: CATEGORIES.RESOURCES,
    factor: 1.5,
    base: {
      metal: 225,
      crystal: 75,
      deuterium: 0,
      energyCost: 0,
      energyConsumption: 20,
      deuteriumConsumption: 0,
      production: 10,
    },
  },
  4: {
    ogameId: 4,
    names: { en: 'Solar Plant', fr: 'Centrale électrique solaire' },
    category: CATEGORIES.RESOURCES,
    factor: 1.5,
    base: {
      metal: 75,
      crystal: 30,
      deuterium: 0,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 20,
    },
  },
  5: {
    ogameId: 12,
    names: { en: 'Fusion Reactor', fr: 'Centrale électrique de fusion' },
    category: CATEGORIES.RESOURCES,
    factor: 1.8,
    base: {
      metal: 900,
      crystal: 360,
      deuterium: 180,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 10,
      production: 30,
    },
  },
  14: {
    ogameId: 14,
    names: { en: 'Robotics Factory', fr: 'Usine de robots' },
    category: CATEGORIES.FACILITIES,
    factor: 2,
    base: {
      metal: 400,
      crystal: 120,
      deuterium: 200,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  15: {
    ogameId: 15,
    names: { en: 'Nanite Factory', fr: 'Usine de nanites' },
    category: CATEGORIES.FACILITIES,
    factor: 2,
    base: {
      metal: 1000000,
      crystal: 500000,
      deuterium: 100000,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  21: {
    ogameId: 21,
    names: { en: 'Shipyard', fr: 'Chantier spatial' },
    category: CATEGORIES.FACILITIES,
    factor: 2,
    base: {
      metal: 400,
      crystal: 200,
      deuterium: 100,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  22: {
    ogameId: 22,
    names: { en: 'Metal Storage', fr: 'Hangar de métal' },
    category: CATEGORIES.RESOURCES,
    factor: 2,
    storage: 'metal',
    base: {
      metal: 1000,
      crystal: 0,
      deuterium: 0,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  23: {
    ogameId: 23,
    names: { en: 'Crystal Storage', fr: 'Hangar de cristal' },
    category: CATEGORIES.RESOURCES,
    factor: 2,
    storage: 'crystal',
    base: {
      metal: 1000,
      crystal: 500,
      deuterium: 0,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  24: {
    ogameId: 24,
    names: { en: 'Deuterium Tank', fr: 'Réservoir de deutérium' },
    category: CATEGORIES.RESOURCES,
    factor: 2,
    storage: 'deuterium',
    base: {
      metal: 1000,
      crystal: 1000,
      deuterium: 0,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  31: {
    ogameId: 31,
    names: { en: 'Research Lab', fr: 'Laboratoire de recherche' },
    category: CATEGORIES.FACILITIES,
    factor: 2,
    base: {
      metal: 200,
      crystal: 400,
      deuterium: 200,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  33: {
    ogameId: 33,
    names: { en: 'Terraformer', fr: 'Terraformeur' },
    category: CATEGORIES.FACILITIES,
    factor: 2,
    base: {
      metal: 0,
      crystal: 50000,
      deuterium: 100000,
      energyCost: 1000,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  34: {
    ogameId: 34,
    names: { en: 'Alliance Depot', fr: 'Dépôt de ravitaillement' },
    category: CATEGORIES.FACILITIES,
    factor: 2,
    base: {
      metal: 20000,
      crystal: 40000,
      deuterium: 0,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  36: {
    ogameId: 36,
    names: { en: 'Space Dock', fr: 'Dock spatial' },
    category: CATEGORIES.FACILITIES,
    factor: 5,
    // The space dock is the only building whose energy cost grows on its own
    // factor, hence the extra `energyFactor`.
    energyFactor: 2.5,
    base: {
      metal: 200,
      crystal: 0,
      deuterium: 50,
      energyCost: 50,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  41: {
    ogameId: 41,
    names: { en: 'Lunar Base', fr: 'Base lunaire' },
    category: CATEGORIES.MOON,
    factor: 2,
    base: {
      metal: 20000,
      crystal: 40000,
      deuterium: 20000,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  42: {
    ogameId: 42,
    names: { en: 'Sensor Phalanx', fr: 'Phalange de capteur' },
    category: CATEGORIES.MOON,
    factor: 2,
    base: {
      metal: 20000,
      crystal: 40000,
      deuterium: 20000,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  43: {
    ogameId: 43,
    names: { en: 'Jump Gate', fr: 'Porte de saut spatial' },
    category: CATEGORIES.MOON,
    factor: 2,
    base: {
      metal: 2000000,
      crystal: 4000000,
      deuterium: 2000000,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
  44: {
    ogameId: 44,
    names: { en: 'Missile Silo', fr: 'Silo de missiles' },
    category: CATEGORIES.FACILITIES,
    factor: 2,
    base: {
      metal: 20000,
      crystal: 20000,
      deuterium: 1000,
      energyCost: 0,
      energyConsumption: 0,
      deuteriumConsumption: 0,
      production: 0,
    },
  },
});

export { CATEGORIES };
export default BUILDINGS;
