const ATTRIBUTES = Object.freeze({
  TYPES: {
    ATTACK: 'attack',
    CIVIL: 'civil',
    DEFENSE: 'defense',
  },
  CATEGORIES: {
    SHIPS: 'ships',
    DEFENSES: 'defenses',
    MISSILE: 'missiles',
  },
  DRIVES: {
    COMBUSTION: 'combustion',
    IMPULSE: 'impulse',
    HYPERSPACE: 'hyperspace',
    NONE: 'none',
  },
});

/**
 * Every ship, defense and missile of the game, keyed by the id used by this
 * library. `ogameId` holds the official OGame id (204 for the light fighter,
 * 401 for the rocket launcher, ...) and is the field to rely on when talking
 * to the game.
 *
 * - `names` holds the localised labels.
 * - `structure` is the metal plus crystal cost; hull points are a tenth of it.
 * - `speed` is the base speed, before any drive technology bonus.
 * - `cargo` is the cargo capacity, `fuelConsumption` the base deuterium burned.
 * - `drive` is the technology powering the ship, `driveUpgrades` the drives it
 *   switches to once the matching technology is high enough.
 * - `rapidFire` lists the rapid-fire bonuses against other entries of this model,
 *   `target` being a library id.
 */
const DESTROYABLE = Object.freeze({
  1: {
    ogameId: 204,
    names: { en: 'Light Fighter', fr: 'Chasseur léger' },
    structure: 4000,
    shield: 10,
    attack: 50,
    speed: 12500,
    cargo: 50,
    fuelConsumption: 20,
    drive: ATTRIBUTES.DRIVES.COMBUSTION,
    type: ATTRIBUTES.TYPES.ATTACK,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
    ],
    cost: {
      metal: 3000,
      crystal: 1000,
      deuterium: 0,
    },
  },
  2: {
    ogameId: 205,
    names: { en: 'Heavy Fighter', fr: 'Chasseur lourd' },
    structure: 10000,
    shield: 25,
    attack: 150,
    speed: 10000,
    cargo: 100,
    fuelConsumption: 75,
    drive: ATTRIBUTES.DRIVES.IMPULSE,
    type: ATTRIBUTES.TYPES.ATTACK,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 11,
        fire: 3,
      },
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
    ],
    cost: {
      metal: 6000,
      crystal: 4000,
      deuterium: 0,
    },
  },
  3: {
    ogameId: 206,
    names: { en: 'Cruiser', fr: 'Croiseur' },
    structure: 27000,
    shield: 50,
    attack: 400,
    speed: 15000,
    cargo: 800,
    fuelConsumption: 300,
    drive: ATTRIBUTES.DRIVES.IMPULSE,
    type: ATTRIBUTES.TYPES.ATTACK,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 1,
        fire: 6,
      },
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
      {
        target: 201,
        fire: 10,
      },
    ],
    cost: {
      metal: 20000,
      crystal: 7000,
      deuterium: 2000,
    },
  },
  4: {
    ogameId: 207,
    names: { en: 'Battleship', fr: 'Vaisseau de bataille' },
    structure: 60000,
    shield: 200,
    attack: 1000,
    speed: 10000,
    cargo: 1500,
    fuelConsumption: 500,
    drive: ATTRIBUTES.DRIVES.HYPERSPACE,
    type: ATTRIBUTES.TYPES.ATTACK,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
    ],
    cost: {
      metal: 45000,
      crystal: 15000,
      deuterium: 0,
    },
  },
  5: {
    ogameId: 215,
    names: { en: 'Battlecruiser', fr: 'Traqueur' },
    structure: 70000,
    shield: 400,
    attack: 700,
    speed: 10000,
    cargo: 750,
    fuelConsumption: 250,
    drive: ATTRIBUTES.DRIVES.HYPERSPACE,
    type: ATTRIBUTES.TYPES.ATTACK,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 2,
        fire: 4,
      },
      {
        target: 3,
        fire: 4,
      },
      {
        target: 4,
        fire: 7,
      },
      {
        target: 11,
        fire: 3,
      },
      {
        target: 12,
        fire: 3,
      },
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
    ],
    cost: {
      metal: 30000,
      crystal: 40000,
      deuterium: 15000,
    },
  },
  6: {
    ogameId: 211,
    names: { en: 'Bomber', fr: 'Bombardier' },
    structure: 75000,
    shield: 500,
    attack: 1000,
    speed: 4000,
    cargo: 500,
    fuelConsumption: 700,
    drive: ATTRIBUTES.DRIVES.IMPULSE,
    driveUpgrades: [
      {
        drive: ATTRIBUTES.DRIVES.HYPERSPACE,
        minLevel: 8,
        speed: 5000,
        fuelConsumption: 1000,
      },
    ],
    type: ATTRIBUTES.TYPES.ATTACK,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
      {
        target: 201,
        fire: 20,
      },
      {
        target: 202,
        fire: 20,
      },
      {
        target: 203,
        fire: 10,
      },
      {
        target: 204,
        fire: 5,
      },
      {
        target: 205,
        fire: 10,
      },
      {
        target: 206,
        fire: 5,
      },
    ],
    cost: {
      metal: 50000,
      crystal: 25000,
      deuterium: 15000,
    },
  },
  7: {
    ogameId: 213,
    names: { en: 'Destroyer', fr: 'Destructeur' },
    structure: 110000,
    shield: 500,
    attack: 2000,
    speed: 5000,
    cargo: 2000,
    fuelConsumption: 1000,
    drive: ATTRIBUTES.DRIVES.HYPERSPACE,
    type: ATTRIBUTES.TYPES.ATTACK,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
      {
        target: 5,
        fire: 2,
      },
      {
        target: 202,
        fire: 10,
      },
    ],
    cost: {
      metal: 60000,
      crystal: 50000,
      deuterium: 15000,
    },
  },
  8: {
    ogameId: 214,
    names: { en: 'Deathstar', fr: 'Étoile de la mort' },
    structure: 9000000,
    shield: 50000,
    attack: 200000,
    speed: 100,
    cargo: 1000000,
    fuelConsumption: 1,
    drive: ATTRIBUTES.DRIVES.HYPERSPACE,
    type: ATTRIBUTES.TYPES.ATTACK,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 1,
        fire: 200,
      },
      {
        target: 2,
        fire: 100,
      },
      {
        target: 3,
        fire: 33,
      },
      {
        target: 4,
        fire: 30,
      },
      {
        target: 5,
        fire: 15,
      },
      {
        target: 6,
        fire: 25,
      },
      {
        target: 7,
        fire: 5,
      },
      {
        target: 9,
        fire: 10,
      },
      {
        target: 10,
        fire: 30,
      },
      {
        target: 11,
        fire: 250,
      },
      {
        target: 12,
        fire: 250,
      },
      {
        target: 13,
        fire: 250,
      },
      {
        target: 14,
        fire: 250,
      },
      {
        target: 15,
        fire: 1250,
      },
      {
        target: 16,
        fire: 1250,
      },
      {
        target: 17,
        fire: 1250,
      },
      {
        target: 201,
        fire: 200,
      },
      {
        target: 202,
        fire: 200,
      },
      {
        target: 203,
        fire: 100,
      },
      {
        target: 204,
        fire: 50,
      },
      {
        target: 205,
        fire: 100,
      },
    ],
    cost: {
      metal: 5000000,
      crystal: 4000000,
      deuterium: 1000000,
    },
  },
  9: {
    ogameId: 218,
    names: { en: 'Reaper', fr: 'Faucheur' },
    structure: 140000,
    shield: 700,
    attack: 2800,
    speed: 7000,
    cargo: 10000,
    fuelConsumption: 1100,
    drive: ATTRIBUTES.DRIVES.HYPERSPACE,
    type: ATTRIBUTES.TYPES.ATTACK,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
      {
        target: 4,
        fire: 7,
      },
      {
        target: 6,
        fire: 4,
      },
      {
        target: 7,
        fire: 3,
      },
    ],
    cost: {
      metal: 85000,
      crystal: 55000,
      deuterium: 20000,
    },
  },
  10: {
    ogameId: 219,
    names: { en: 'Pathfinder', fr: 'Éclaireur' },
    structure: 23000,
    shield: 100,
    attack: 200,
    speed: 12000,
    cargo: 10000,
    fuelConsumption: 300,
    drive: ATTRIBUTES.DRIVES.HYPERSPACE,
    type: ATTRIBUTES.TYPES.ATTACK,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 1,
        fire: 3,
      },
      {
        target: 2,
        fire: 2,
      },
      {
        target: 3,
        fire: 3,
      },
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
    ],
    cost: {
      metal: 8000,
      crystal: 15000,
      deuterium: 8000,
    },
  },
  11: {
    ogameId: 202,
    names: { en: 'Small Cargo', fr: 'Petit transporteur' },
    structure: 4000,
    shield: 10,
    attack: 5,
    speed: 5000,
    cargo: 5000,
    fuelConsumption: 10,
    drive: ATTRIBUTES.DRIVES.COMBUSTION,
    driveUpgrades: [
      {
        drive: ATTRIBUTES.DRIVES.IMPULSE,
        minLevel: 5,
        speed: 10000,
        fuelConsumption: 20,
      },
    ],
    type: ATTRIBUTES.TYPES.CIVIL,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
    ],
    cost: {
      metal: 2000,
      crystal: 2000,
      deuterium: 0,
    },
  },
  12: {
    ogameId: 203,
    names: { en: 'Large Cargo', fr: 'Grand transporteur' },
    structure: 12000,
    shield: 25,
    attack: 5,
    speed: 7500,
    cargo: 25000,
    fuelConsumption: 50,
    drive: ATTRIBUTES.DRIVES.COMBUSTION,
    type: ATTRIBUTES.TYPES.CIVIL,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
    ],
    cost: {
      metal: 6000,
      crystal: 6000,
      deuterium: 0,
    },
  },
  13: {
    ogameId: 208,
    names: { en: 'Colony Ship', fr: 'Vaisseau de colonisation' },
    structure: 30000,
    shield: 100,
    attack: 50,
    speed: 2500,
    cargo: 7500,
    fuelConsumption: 1000,
    drive: ATTRIBUTES.DRIVES.IMPULSE,
    type: ATTRIBUTES.TYPES.CIVIL,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
    ],
    cost: {
      metal: 10000,
      crystal: 20000,
      deuterium: 10000,
    },
  },
  14: {
    ogameId: 209,
    names: { en: 'Recycler', fr: 'Recycleur' },
    structure: 16000,
    shield: 10,
    attack: 1,
    speed: 2000,
    cargo: 20000,
    fuelConsumption: 300,
    drive: ATTRIBUTES.DRIVES.COMBUSTION,
    driveUpgrades: [
      {
        drive: ATTRIBUTES.DRIVES.IMPULSE,
        minLevel: 17,
        speed: 4000,
        fuelConsumption: 600,
      },
      {
        drive: ATTRIBUTES.DRIVES.HYPERSPACE,
        minLevel: 15,
        speed: 6000,
        fuelConsumption: 900,
      },
    ],
    type: ATTRIBUTES.TYPES.CIVIL,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [
      {
        target: 15,
        fire: 5,
      },
      {
        target: 16,
        fire: 5,
      },
      {
        target: 17,
        fire: 5,
      },
    ],
    cost: {
      metal: 10000,
      crystal: 6000,
      deuterium: 2000,
    },
  },
  15: {
    ogameId: 210,
    names: { en: 'Espionage Probe', fr: "Sonde d'espionnage" },
    structure: 1000,
    shield: 0,
    attack: 0,
    speed: 100000000,
    cargo: 5,
    fuelConsumption: 1,
    drive: ATTRIBUTES.DRIVES.COMBUSTION,
    type: ATTRIBUTES.TYPES.CIVIL,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [],
    cost: {
      metal: 0,
      crystal: 1000,
      deuterium: 0,
    },
  },
  16: {
    ogameId: 212,
    names: { en: 'Solar Satellite', fr: 'Satellite solaire' },
    structure: 2000,
    shield: 1,
    attack: 1,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.CIVIL,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [],
    cost: {
      metal: 0,
      crystal: 2000,
      deuterium: 500,
    },
  },
  17: {
    ogameId: 217,
    names: { en: 'Crawler', fr: 'Foreuse' },
    structure: 4000,
    shield: 1,
    attack: 1,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.CIVIL,
    category: ATTRIBUTES.CATEGORIES.SHIPS,
    rapidFire: [],
    cost: {
      metal: 2000,
      crystal: 2000,
      deuterium: 1000,
    },
  },
  201: {
    ogameId: 401,
    names: { en: 'Rocket Launcher', fr: 'Lanceur de missiles' },
    structure: 2000,
    shield: 20,
    attack: 80,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.DEFENSE,
    category: ATTRIBUTES.CATEGORIES.DEFENSES,
    rapidFire: [],
    cost: {
      metal: 2000,
      crystal: 0,
      deuterium: 0,
    },
  },
  202: {
    ogameId: 402,
    names: { en: 'Light Laser', fr: 'Artillerie laser légère' },
    structure: 2000,
    shield: 25,
    attack: 100,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.DEFENSE,
    category: ATTRIBUTES.CATEGORIES.DEFENSES,
    rapidFire: [],
    cost: {
      metal: 1500,
      crystal: 500,
      deuterium: 0,
    },
  },
  203: {
    ogameId: 403,
    names: { en: 'Heavy Laser', fr: 'Artillerie laser lourde' },
    structure: 8000,
    shield: 100,
    attack: 250,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.DEFENSE,
    category: ATTRIBUTES.CATEGORIES.DEFENSES,
    rapidFire: [],
    cost: {
      metal: 6000,
      crystal: 2000,
      deuterium: 0,
    },
  },
  204: {
    ogameId: 404,
    names: { en: 'Gauss Cannon', fr: 'Canon de Gauss' },
    structure: 35000,
    shield: 200,
    attack: 1100,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.DEFENSE,
    category: ATTRIBUTES.CATEGORIES.DEFENSES,
    rapidFire: [],
    cost: {
      metal: 20000,
      crystal: 15000,
      deuterium: 2000,
    },
  },
  205: {
    ogameId: 405,
    names: { en: 'Ion Cannon', fr: 'Artillerie à ions' },
    structure: 8000,
    shield: 500,
    attack: 150,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.DEFENSE,
    category: ATTRIBUTES.CATEGORIES.DEFENSES,
    rapidFire: [
      {
        target: 9,
        fire: 2,
      },
    ],
    cost: {
      metal: 5000,
      crystal: 3000,
      deuterium: 0,
    },
  },
  206: {
    ogameId: 406,
    names: { en: 'Plasma Turret', fr: 'Lanceur de plasma' },
    structure: 100000,
    shield: 300,
    attack: 3000,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.DEFENSE,
    category: ATTRIBUTES.CATEGORIES.DEFENSES,
    rapidFire: [],
    cost: {
      metal: 50000,
      crystal: 50000,
      deuterium: 30000,
    },
  },
  207: {
    ogameId: 407,
    names: { en: 'Small Shield Dome', fr: 'Petit bouclier' },
    structure: 20000,
    shield: 2000,
    attack: 1,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.DEFENSE,
    category: ATTRIBUTES.CATEGORIES.DEFENSES,
    rapidFire: [],
    cost: {
      metal: 10000,
      crystal: 10000,
      deuterium: 0,
    },
  },
  208: {
    ogameId: 408,
    names: { en: 'Large Shield Dome', fr: 'Grand bouclier' },
    structure: 100000,
    shield: 10000,
    attack: 1,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.DEFENSE,
    category: ATTRIBUTES.CATEGORIES.DEFENSES,
    rapidFire: [],
    cost: {
      metal: 50000,
      crystal: 50000,
      deuterium: 0,
    },
  },
  301: {
    ogameId: 502,
    names: { en: 'Anti-Ballistic Missile', fr: "Missile d'interception" },
    structure: 8000,
    shield: 1,
    attack: 1,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.DEFENSE,
    category: ATTRIBUTES.CATEGORIES.MISSILE,
    rapidFire: [],
    cost: {
      metal: 8000,
      crystal: 0,
      deuterium: 2000,
    },
  },
  302: {
    ogameId: 503,
    names: { en: 'Interplanetary Missile', fr: 'Missile interplanétaire' },
    structure: 15000,
    shield: 1,
    attack: 12000,
    speed: 0,
    cargo: 0,
    fuelConsumption: 0,
    drive: ATTRIBUTES.DRIVES.NONE,
    type: ATTRIBUTES.TYPES.DEFENSE,
    category: ATTRIBUTES.CATEGORIES.MISSILE,
    rapidFire: [],
    cost: {
      metal: 12500,
      crystal: 2500,
      deuterium: 10000,
    },
  },
});

export { ATTRIBUTES };
export default DESTROYABLE;
